services:
  - type: web
    name: qrScannerReader
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libzbar0
      pip install -r requirements.txt
    startCommand: gunicorn app:app
